
trigger:
- master

pool:
  name: Default

stages:
 - stage: build
   jobs:
   - job: buildjob
     steps:
      - script: mvn package


 - stage: deploytoapp
   jobs:
   - job: deployjob
     steps:
     - task: AzureRmWebAppDeployment@5
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'resourcegroup'
         appType: 'webApp'
         WebAppName: 'sdfregx'
         packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'



 
